# Generated by Django 3.0.3 on 2020-02-29 06:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='cols',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='players',
            name='major',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='players',
            name='minor',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='players',
            name='rows',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
