# Generated by Django 3.0.3 on 2020-02-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0002_auto_20200229_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Players',
        ),
    ]
