# Generated by Django 3.0.3 on 2020-02-29 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0003_delete_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('cols', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('major', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('minor', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
    ]
