# Generated by Django 3.0.3 on 2020-02-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0004_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='major',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='players',
            name='minor',
            field=models.IntegerField(default=0),
        ),
    ]
