# Generated by Django 3.0.3 on 2020-02-29 07:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0005_auto_20200229_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='cols',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[0, 0, 0]),
        ),
        migrations.AlterField(
            model_name='players',
            name='rows',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[0, 0, 0]),
        ),
    ]
