# Generated by Django 3.0.3 on 2020-02-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0007_auto_20200229_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
