# Generated by Django 3.0.3 on 2020-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0008_players_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='roster',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='roster',
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='GameState',
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
