# Generated by Django 3.0.4 on 2020-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0009_auto_20200304_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='human_player_name',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='draws',
            new_name='moves',
        ),
        migrations.RemoveField(
            model_name='history',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='history',
            name='wins',
        ),
        migrations.AddField(
            model_name='history',
            name='result',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
