# Generated by Django 3.0.4 on 2020-03-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0010_auto_20200305_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='last_played',
            new_name='timestamp',
        ),
    ]
