# Generated by Django 3.0.4 on 2020-03-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0011_auto_20200310_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='human_player_name',
            new_name='name',
        ),
    ]
