# Generated by Django 3.0.4 on 2020-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0012_auto_20200310_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='human',
            field=models.BooleanField(default=False),
        ),
    ]
